### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by yangpin** [cokuscz/audioWaveCanvas#2]
NullPointerException
WaveformView.millisecsToPixels(int)' on a null object reference
播放录制内容，更新waveView的时候

**Comment by cokuscz** [comment]
这个你能重现吗？ @yangpin  如果能那你描述下，谢谢！

**Comment by yangpin** [comment]
我这边首先是录制音乐，录制成功后跳转至播放页，播放页返回的时候 就会引发这个异常，updateDisplay() 方法里面的， int frames = mWaveView.millisecsToPixels(now)；这个方法引发的，应该是那个zoom数组的问题，里面的代码我还看的不是太懂，希望大神有空看下 谢谢！

**Comment by cokuscz** [comment]
我今天试了一下 没有复现你的问题，但是我觉得我这个实时绘制还是有一定问题，感觉数据多会卡顿，没有做surfaceview局部更新，所以我今天看你那个问题也思考了准备用view去做实时更新效果会更好。

**Comment by yangpin** [comment]
恩恩 谢谢，我也会认真看你的代码的，具体看问题在哪，再反馈 。
